# Generated by Django 4.2.17 on 2024-12-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faixa_etaria_2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_companhia', models.TextField(blank=True, db_column='CNPJ_Companhia', null=True)),
                ('data_referencia', models.TextField(blank=True, db_column='Data_Referencia', null=True)),
                ('versao', models.IntegerField(blank=True, db_column='Versao', null=True)),
                ('id_documento', models.IntegerField(blank=True, db_column='ID_Documento', null=True)),
                ('nome_companhia', models.TextField(blank=True, db_column='Nome_Companhia', null=True)),
                ('local', models.TextField(blank=True, db_column='Local', null=True)),
                ('quantidade_ate30anos', models.IntegerField(blank=True, db_column='Quantidade_Ate30Anos', null=True)),
                ('quantidade_30a50anos', models.IntegerField(blank=True, db_column='Quantidade_30a50Anos', null=True)),
                ('quantidade_acima50anos', models.IntegerField(blank=True, db_column='Quantidade_Acima50Anos', null=True)),
            ],
            options={
                'db_table': 'faixa_etaria_2024',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='declaracao_genero_2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_companhia', models.TextField(blank=True, db_column='CNPJ_Companhia', null=True)),
                ('data_referencia', models.TextField(blank=True, db_column='Data_Referencia', null=True)),
                ('versao', models.IntegerField(blank=True, db_column='Versao', null=True)),
                ('id_documento', models.IntegerField(blank=True, db_column='ID_Documento', null=True)),
                ('nome_companhia', models.TextField(blank=True, db_column='Nome_Companhia', null=True)),
                ('local', models.TextField(blank=True, db_column='Local', null=True)),
                ('quantidade_feminino', models.IntegerField(blank=True, db_column='Quantidade_Feminino', null=True)),
                ('quantidade_masculino', models.IntegerField(blank=True, db_column='Quantidade_Masculino', null=True)),
                ('quantidade_nao_binario', models.IntegerField(blank=True, db_column='Quantidade_Nao_Binario', null=True)),
                ('quantidade_outros', models.IntegerField(blank=True, db_column='Quantidade_Outros', null=True)),
                ('quantidade_sem_resposta', models.IntegerField(blank=True, db_column='Quantidade_Sem_Resposta', null=True)),
            ],
            options={
                'db_table': 'declaracao_genero_2024',
            },
        ),
        migrations.CreateModel(
            name='declaracao_raca_2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_companhia', models.TextField(blank=True, db_column='CNPJ_Companhia', null=True)),
                ('data_referencia', models.TextField(blank=True, db_column='Data_Referencia', null=True)),
                ('versao', models.IntegerField(blank=True, db_column='Versao', null=True)),
                ('id_documento', models.IntegerField(blank=True, db_column='ID_Documento', null=True)),
                ('nome_companhia', models.TextField(blank=True, db_column='Nome_Companhia', null=True)),
                ('local', models.TextField(blank=True, db_column='Local', null=True)),
                ('quantidade_amarelo', models.IntegerField(blank=True, db_column='Quantidade_Amarelo', null=True)),
                ('quantidade_branco', models.IntegerField(blank=True, db_column='Quantidade_Branco', null=True)),
                ('quantidade_preto', models.IntegerField(blank=True, db_column='Quantidade_Preto', null=True)),
                ('quantidade_pardo', models.IntegerField(blank=True, db_column='Quantidade_Pardo', null=True)),
                ('quantidade_indigena', models.IntegerField(blank=True, db_column='Quantidade_Indigena', null=True)),
                ('quantidade_outros', models.IntegerField(blank=True, db_column='Quantidade_Outros', null=True)),
                ('quantidade_sem_resposta', models.IntegerField(blank=True, db_column='Quantidade_Sem_Resposta', null=True)),
            ],
            options={
                'db_table': 'declaracao_raca_2024',
            },
        ),
    ]
